### ISSUE TITLE
Impossible to init in javascript

### ISSUE THREAD

**Issue by alistarle** [kartik-v/bootstrap-popover-x#15]
Hello, 

After looking for so many hours to all the documentation available, it is impossible to me to init the plugin with the .popoverX() function.

Here'is my code

```html
<!-- jQuery -->
<script src="bower_components/jquery/jquery.min.js"></script>
<!-- external javascript -->
<script src="js/bootstrap.js"></script>
<script src="js/bootstrap-popover-x.js" type="text/javascript"></script>

<button class="btn btn-primary" data-toggle="popover-x" data-target="#myPopover1" data-placement="top">Top</button>
<div id="myPopover1" class="popover popover-default">
    <div class="arrow"></div>
    <div class="popover-title"><span class="close pull-right" data-dismiss="popover-x">&times;</span>Title</div>
    <div class="popover-content">
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.</p>
    </div>
</div>

<script type="text/javascript">
	$("#myPopover1").popoverX();
</script>
```

And the error i have
Uncaught TypeError: Cannot read property '$target' of undefined, line 120 of your js

if i use the following code 

```html
<script type="text/javascript">
	$("#myPopover1").popoverX("show");
</script>
```

I have the following error 
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined, line 52 of your js

**Comment by kartik-v** [comment]
Note popover-x is initialized just like bootstrap modal as mentioned in docs.

If you are setting data attributes `data-toggle = "popover-x"` - then the popoverX plugin will auto initialize. You should not therefore be initializing the plugin via javascript again. That is probably causing the issue. Just remove the `script` code that contains the `$("#myPopover1").popoverX` and try,

**Comment by alistarle** [comment]
If i remove the button, i've still the Uncaught TypeError: Cannot read property 'offsetWidth' of undefined error. The popover correctly display but at the top-left of the page, and the show.bs.modal event don't fire so i can't update the content in ajax. 

I must use the javascript method because my button are changed in ajax, so the data attribute don't launch popover anymore

**Comment by kartik-v** [comment]
If you are using javascript to initialize... you must call the javascript on document ready.

Instead of directly calling `$("#myPopover1").popoverX();`

you must try something like:

```js
$(document).on('ready', function() {
   var options = {}; // set your plugin options
    $("#myPopover1").popoverX(options);
});
```

**Comment by alistarle** [comment]
Your code display nothing but there is no error triggered, anyway, when i try to use $("#myPopover1").popoverX("show"); juste after the init line, it display the popover with the error i described previously

**Comment by Webkadabra** [comment]
I'm running in the same issue, having my popoverX containers and triggers generated via ajax, i can't make popoverX initiate as well

**Comment by Webkadabra** [comment]
I basically copied code from popoverx.js in $(document).ready() and it worked well :)!

**Comment by Webkadabra** [comment]
```
$("#someDynamicallyAddedElement").on('click', function (e) {
            var $this = $(this), href = $this.attr('href'),
                $dialog = $($this.attr('data-target') || (href && href.replace(/.*(?=#[^\s]+$)/, ''))), //strip for ie7
                option = $dialog.data('popover-x') ? 'toggle' : $.extend({remote: !/#/.test(href) && href},
                    $dialog.data(), $this.data());
            e.preventDefault();
            $dialog.trigger('click.target.popoverX');
            if (option !== 'toggle') {
                option.$target = $this;
                $dialog
                    .popoverX(option)
                    .popoverX('show')
                    .on('hide', function () {
                        $this.focus();
                    });
            }
            else {
                $dialog
                    .popoverX(option)
                    .on('hide', function () {
                        $this.focus();
                    });
            }
        });
```

**Comment by kartik-v** [comment]
Refer enhancments #24 and #25 that will solve this in the next release.
