### ISSUE TITLE
Bug when calling from jquery?

### ISSUE THREAD

**Issue by mscreenie** [kartik-v/bootstrap-popover-x#16]
I get this error in console

Uncaught TypeError: Cannot read property 'offsetWidth' of undefined

$('#myPopover1').popoverX({
        closeOtherPopovers: false
    });

Any config options causes this error. Any ideas?

**Comment by liamhughes** [comment]
+1
I am seeing this as well.

**Comment by majksner** [comment]
+1

**Comment by kartik-v** [comment]
You need to load `bootstrap.js` before this (as this plugin depends on bootstrap modal).

**Comment by jos0003** [comment]
When initialising popover, you need to set ```$target``` to the target element you want (so that it can get the position/offset values).

    $('#myPopover').popoverX({
        show: false,
        $target: $('#btn-element')
    });
