### ISSUE TITLE
Will be great if add auto placement feature...

### ISSUE THREAD

**Issue by oimken** [kartik-v/bootstrap-popover-x#21]
I think auto placement is very useful feature,
please consider to add it to bootstrap-popover-x.

I try to get auto placement from @sandywalker 
https://github.com/sandywalker/webui-popover

it seems works.
https://github.com/kartik-v/bootstrap-popover-x/compare/master...oimken:test

**Comment by kartik-v** [comment]
This will be resolved via latest release (also refer other enhancements #24, #25, and #26).

**Comment by kartik-v** [comment]
Resolved via [updates to release v1.4.2](https://github.com/kartik-v/bootstrap-popover-x/commit/281756673b83c367b0651b7d8410c81464b032e0).
