### ISSUE TITLE
Rebind widget after ajax reload

### ISSUE THREAD

**Issue by dacom-dark-sun** [kartik-v/bootstrap-popover-x#27]
Hello, Kartik!
After reload page with ajax widget popover, of course, not active.. How i can re-init popover widget after ajax reload? I have tried re-bind it again like that:  
> $('#popover').popover(); 

But this is wrong.. What the right way with your widget?

**Comment by kartik-v** [comment]
Use `popoverButton` plugin - and refer to [the example for initialization of plugin via javascript in the demos advanced usage section](http://plugins.krajee.com/popover-x/demo#advanced-usage).
