### ISSUE TITLE
"DIV IS" problem

### ISSUE THREAD

**Issue by dacom-dark-sun** [kartik-v/bootstrap-popover-x#28]
Hello Kartik!
I have strange problem with your widget, which happen after move to production server. 
Under div with popover, i see: 
`<div is="[object Object]"></div>`

Widget still working, but my layout is destroyed, particularly on mobile devices.
In develop server i don`t have this div and i cant determine from where this div appeared.. I check versions in composer, they are same.. I can not imagine where it came from. Any suggestions?

**Comment by kartik-v** [comment]
You may need to check your code and other javascript that might be rendering the above markup.
