### ISSUE TITLE
More intuitive screen placement depending on media size

### ISSUE THREAD

**Issue by radiantone** [kartik-v/bootstrap-popover-x#30]
Hi,
  I specify "left" as my position, which displays correctly on wide screen. It would be nice if the popover would auto locate itself when (or as) the screen size shrinks, so it is not offscreen. Or, similarly, a position setting that tries to position the popover in a preferred location (e.g. left), but if there is not enough room to do so, then fall back on auto.  Or lastly, allow me to set the position based on device media size. so I can pre-define which position setting to use depending on which @media size is currently active. I read over the docs for the placement and tried some of them but none fit my needs exactly. If I overlooked the answer to this, my early regrets.

Thanks

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest `master` branch of bootstrap-popover-x.
- [X ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/popover-x) and [demos](http://plugins.krajee.com/popover-x/demo).
- [X ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-popover-x version:

## Isolating the problem

- [ ] This bug happens [on the plugin demos page](http://plugins.krajee.com/popover-x/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-popover-x without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
You need to try configuring one of the auto placement options for your use case as highlighted in the [second example of basic usage](http://plugins.krajee.com/popover-x/demo). 

The placement options are the only way currently to configure the plugin for your application design needs. Try out one of the placement options that suits you.

**Comment by radiantone** [comment]
I did try auto-left. And it didn't work. off master branch. That's why I created this ticket. When the screen is made smaller the popup appears off screen. It shouldn't.

**Comment by kartik-v** [comment]
I am reopening this issue for enhancement. Will need time to study this. Feel free to add in your thoughts or changes to the CSS>

**Comment by radiantone** [comment]
Ok. Thank you.

Here's a quick approach. Not a good one, but just to show what I did.

Added a dummy class (popoverx) to my popover element.

                <a href="#" class="popoverx" data-toggle="popover-x" data-target="#myPopover1"
                   data-placement="auto-left">Title 14</a>

Then in my app, I add a resize detector. If width is less than a certain amount, change the placement.
It may not be possible to compute the width of the popup before displaying it in order to select best placement. But this is very specific to my app so its not a general solution.

> $( window ).resize(function() {
        if ($(window).width() <= 1500) {
            $('.popoverx').attr("data-placement","top top-left");
        } else {
            $('.popoverx').attr("data-placement","auto-left");
        }
    });

In popx.getPlacement() I override the placement attribute by getting it dynamically. Currently it stores the placement in options and even if the element changes, it is not updated. So this is not "responsive" to changes in window size, etc.

> getPlacement: function () {
            var self = this, pos = self.getPosition(), placement = self.options.placement,
                de = document.documentElement, db = document.body, cw = de.clientWidth, ch = de.clientHeight,
                scrollTop = Math.max(db.scrollTop || 0, de.scrollTop), isH = placement === 'horizontal',
                scrollLeft = Math.max(db.scrollLeft || 0, de.scrollLeft), isV = placement === 'vertical',
                pageX = Math.max(0, pos.left - scrollLeft), pageY = Math.max(0, pos.top - scrollTop),
                autoPlace = placement === 'auto' || isH || isV;

            var placement = $(this.$target).attr("data-placement");

**Comment by kartik-v** [comment]
Refer also the [CHANGE log](https://github.com/kartik-v/bootstrap-popover-x/blob/master/CHANGE.md) for the changes to achieve this.

**Comment by radiantone** [comment]
Thank you for this. I really appreciate it. Will try it out soon.
