### ISSUE TITLE
On the demo webpage, page moves when widget is clicked

### ISSUE THREAD

**Issue by newadventure079** [kartik-v/bootstrap-popover-x#47]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of bootstrap-popover-x.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/popover-x) and [demos](http://plugins.krajee.com/popover-x/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
Go to https://plugins.krajee.com/popover-x/demo and click on the first widget
The page moves down

![Screenflick Movie 4](https://user-images.githubusercontent.com/84156407/184999332-104a6561-910f-4479-9428-c2db3095ea4e.gif)

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-popover-x version:

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/popover-x/demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using bootstrap-popover-x without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kartik-v** [comment]
This is an issue because of some updates to bootstrap library which breaks the plugin (applicable for Bootstrap versions > v5.1.3)... will be fixed for newer versions.
